backend:
  name: git-gateway
  branch: main # The branch where the content files are stored

media_folder: "uploads" # Folder where images will be uploaded
public_folder: "/uploads" # Folder where images will be served from

collections:
  - name: "posts"
    label: "Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
